apiVersion : apps/v1
kind: Deployment
metadata:
  name: app1nginx1902 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1nginx1902
  template:
    metadata:
      labels:
        app: app1nginx1902 
    spec:
      containers:
        - name: app1nginx1902 
          image: aksdevopsacrpbs.azurecr.io/app1nginx1902
          ports:
          - containerPort: 80